#!/bin/bash
ARG=$1
FILE=/home/$USER/messages.log

case "$ARG" in
    clear) cat /dev/null > $FILE
        ;;
    count) echo $(wc -l $FILE | awk '{print $1}')
        ;;
    irc) USER=$2
        shift 2
        MESSAGE=$@
        echo $(date '+%Y/%m/%d %H:%M') IRC - $USER : "$MESSAGE" >> $FILE
        notify-send "irc - $USER: " "$(echo $MESSAGE | cut -c1-50)"
        ;;
    mpd_current)
        notify-send "♪ currently playing: " "$(mpc current)"
        ;;
    date)
        notify-send "date: " "$(date '+%Y/%m/%d %H:%M')"
        ;;
    volume)
        notify-send "volume: " "$(amixer get Master | sed -n 's/^.*\[\([0-9]\+%\).*$/\1/p' | uniq)"
        ;;
    battery)
        notify-send "battery level: " "$(cat /sys/class/power_supply/BAT0/capacity)"
        ;;
    info)
        notify-send 'system information ' "\n<b>date:</b> $(date '+%Y/%m/%d %H:%M')  | <b>volume:</b> $(amixer get Master | sed -n 's/^.*\[\([0-9]\+%\).*$/\1/p' | uniq) | <b>battery:</b> $(cat /sys/class/power_supply/BAT0/capacity)"
        ;;
    view) COUNT=$(wc -l $FILE | awk '{print $1}')
        tail -n $COUNT $FILE | less
        ;;
esac
